### ISSUE TITLE
Game Review

### ISSUE THREAD

**Issue by chilkacastro** [SamPham2020/ProjectTeam10b#1]
**FIRST OF ALL!! GREAT JOB DOING THIS GAME !**     :)

---------------------------------------------------------------------------------------------------------

**GAME ISSUES:**
1. click **HOUSE BUTTON(NO ERRORS!)** not the RESET BUTTON(GIVES ERRORS!)

Please remind the other testers/players that every time they lose or win the game, they should click the HOUSE BUTTON on the bottom right because if they click the reset button instead-- an error
would appear because the scoring and the heart wouldn't appear as 0 score and 3 heart lives. It follows the scoring and
the life count of the previous game. It doesn't reset correctly.

If someone clicks the reset, plenty of errors would occur.
- cat errors, button errors, rock, and instruction page overlaps when you open instruction (which shouldn't happen at all if someone just resets the game correctly using the HOUSE BUTTON instead of the reset button).

2. **CAT ON TOP OF THE WATER**
The cat doesn't lose a life SOMETIMES when on top of the
water in Level 1. SOMETIMES, it allows me to MOVE UP AND DOWN
if I am on top of the water without dying at all. Also, check out the part 
below and above the islands because I could walk over the water moving from 
LEFT to RIGHT SOMETIMES. 

Level 1 is actually my favorite level.

3. **EAGLE TOUCHING THE CAT** (this happens **SOMETIMES** when the cat is on the road)
When the eagle touches the cat on Level 3, and the cat dies. The cat still appears on the road.
This thing happens to my game too, I also forgot to remove the object. 

4. **EAGLE CLONE**  (appears **SOMETIMES** only)
There is no problem with the eagle and cat interaction(cat still loses a life when it touches the eagle). However, the eagle that appears on the bottom right is adding eagle objects several times.
Also, this eagle clone doesn't appear all the time. It appears SOMETIMES so you need to repeat
it several times in order to see the problem when you are checking your game. 

----------------------------------------------------------------------------------------------------------------

**SUGGESTION:**
1. Fewer bats or reduce the speed of the bat movement
2. Reduce the speed of cars and also the eagles chasing the cat makes level 3 so hard.
Would it be possible to hide from the eagle? Like if the cat is under the bridge(specific x and y position), the eagle can't touch the cat or the eagle disappears.

OR if the cat is hiding below the flag, the eagle disappears.

**BUT BEFORE YOU CONSIDER MY SUGGESTIONS, CHECK WHAT OTHERS HAVE TO SAY FIRST
IN TERMS OF LEVEL DIFFICULTY. MAYBE, I JUST SUCK IN PLAYING YOUR GAME :)**
------------------------------------------------------------------------------------------------------------------

**OVERALL, YOUR GAME IS VERY NICE. I PLAYED IT SEVERAL TIMES
YOUR LEVELS ARE UNIQUE AND DIFFERENT FROM EACH OTHER WHICH MAKES IT
VERY INTERESTING. GREAT JOB!!!! :) 

AND YES, IF WE DO HAVE THE CHANCE TO WORK TOGETHER IN THE FUTURE,
I WOULD LIKE THAT!!**

edit: forgot to insert pictures
![2catslevel3](https://user-images.githubusercontent.com/70527669/101457277-4ded1400-3903-11eb-8059-0e7d772c48f1.png)
![eagle](https://user-images.githubusercontent.com/70527669/101457280-4e85aa80-3903-11eb-9a62-2a625119d59b.png)
![walking](https://user-images.githubusercontent.com/70527669/101457281-4e85aa80-3903-11eb-9d40-2bdfbe18258d.png)
![water2](https://user-images.githubusercontent.com/70527669/101457285-4f1e4100-3903-11eb-9b59-ee250ebea53f.png)

**Comment by SamPham2020** [comment]
Thank you for your review
1) We will trim the transparency of the images better to avoid the cat staying on water without dying.
2) We will look into the remained Cat' image to see if it's on our part or Greenfoot.
3) We will make a timer to make the eagle appeared instead of according to the Cat's position.In that way, Greenfoot won't generate multiple eagles at a time.
4) We will reduce the speed of the obstacles ( bats, cars)
5. We will make a safe zone so eagles and bats cannot touch it.
6. About the reset button, we make it in the perspective of gamer's user, not the one of the developpers' ( which the reset is available). However, we will take it into consideration. That's why the lives and score only reset if user click the home button.
Once again, thank your for your comments/feedbacks which are precious to us.

**Comment by chilkacastro** [comment]
but no need to go fixing everything just like what Miss Tassia said in the live meeting because your game is already playable and its a great game already :)
